// Customer Profile — Custom Object
// Auto-imported from Twenty schema | 45 custom fields
import { defineObject, FieldType } from 'twenty-sdk/define';

export default defineObject({
  nameSingular: 'customerProfile',
  namePlural: 'customerProfiles',
  labelSingular: 'Customer Profile',
  labelPlural: 'Customer Profiles',
  description: 'NewLeaf customer profile — canonical customer record',
  icon: 'IconBox',
  fields: [
    { name: 'hyperswitchVaultId', label: 'Hyperswitch Vault ID', type: FieldType.TEXT, isNullable: true },
    { name: 'email', label: 'Email', type: FieldType.EMAILS, isNullable: true },
    { name: 'addressState', label: 'State', type: FieldType.TEXT, isNullable: true },
    { name: 'creditScore', label: 'Credit Score', type: FieldType.NUMBER, isNullable: true },
    { name: 'name', label: 'Name', type: FieldType.TEXT, isNullable: true },
    { name: 'createdBy', label: 'Created by', type: FieldType.TEXT, isNullable: false },
    { name: 'updatedBy', label: 'Updated by', type: FieldType.TEXT, isNullable: false },
    { name: 'timelineActivities', label: 'Timeline Activities', type: FieldType.RELATION, isNullable: true },
    { name: 'attachments', label: 'Attachments', type: FieldType.RELATION, isNullable: true },
    { name: 'noteTargets', label: 'Note Targets', type: FieldType.RELATION, isNullable: true },
    { name: 'taskTargets', label: 'Task Targets', type: FieldType.RELATION, isNullable: true },
    { name: 'dob', label: 'Date of Birth', type: FieldType.DATE_TIME, isNullable: true },
    { name: 'paymentAmount', label: 'Payment Amount', type: FieldType.NUMBER, isNullable: true },
    { name: 'nmiSubscriptionId', label: 'NMI Subscription ID', type: FieldType.TEXT, isNullable: true },
    { name: 'addressStreet2', label: 'Address Street 2', type: FieldType.TEXT, isNullable: true },
    { name: 'addressStreet1', label: 'Address Street 1', type: FieldType.TEXT, isNullable: true },
    { name: 'programTermMonths', label: 'Program Term (Months)', type: FieldType.NUMBER, isNullable: true },
    { name: 'lastName', label: 'Last Name', type: FieldType.TEXT, isNullable: true },
    { name: 'enrolledAt', label: 'Enrolled At', type: FieldType.DATE_TIME, isNullable: true },
    { name: 'pipelineStage', label: 'Pipeline Stage', type: FieldType.TEXT, isNullable: true },
    { name: 'addressPostcode', label: 'Postcode', type: FieldType.TEXT, isNullable: true },
    { name: 'nmiDayZeroTransactionId', label: 'NMI Day Zero Transaction ID', type: FieldType.TEXT, isNullable: true },
    { name: 'programType', label: 'Program Type', type: FieldType.TEXT, isNullable: true },
    { name: 'addressCountry', label: 'Country', type: FieldType.TEXT, isNullable: true },
    { name: 'nextPaymentDate', label: 'Next Payment Date', type: FieldType.DATE_TIME, isNullable: true },
    { name: 'nmiVaultId', label: 'NMI Vault ID', type: FieldType.TEXT, isNullable: true },
    { name: 'agentEmail', label: 'Agent Email', type: FieldType.EMAILS, isNullable: true },
    { name: 'addressCity', label: 'City', type: FieldType.TEXT, isNullable: true },
    { name: 'phone', label: 'Phone', type: FieldType.PHONES, isNullable: true },
    { name: 'unsecuredDebtAmount', label: 'Unsecured Debt Amount', type: FieldType.NUMBER, isNullable: true },
    { name: 'disputes', label: 'Disputes', type: FieldType.RELATION, isNullable: true },
    { name: 'enrollmentStatus', label: 'Enrollment Status', type: FieldType.SELECT, isNullable: true },
    { name: 'agreements', label: 'Agreements', type: FieldType.RELATION, isNullable: true },
    { name: 'paymentFrequency', label: 'Payment Frequency', type: FieldType.SELECT, isNullable: true },
    { name: 'billingStatus', label: 'Billing Status', type: FieldType.SELECT, isNullable: true },
    { name: 'status', label: 'Status', type: FieldType.SELECT, isNullable: true },
    { name: 'communicationLogs', label: 'Communication Logs', type: FieldType.RELATION, isNullable: true },
    { name: 'billingEvents', label: 'Billing Events', type: FieldType.RELATION, isNullable: true },
    { name: 'forthUserId', label: 'Forth User ID', type: FieldType.TEXT, isNullable: true },
    { name: 'slackUserId', label: 'Slack User ID', type: FieldType.TEXT, isNullable: true },
    { name: 'base44Id', label: 'Base44 ID', type: FieldType.TEXT, isNullable: true },
    { name: 'freshcallerContactId', label: 'Freshcaller Contact ID', type: FieldType.TEXT, isNullable: true },
    { name: 'hyperswitchCustomerId', label: 'Hyperswitch Customer ID', type: FieldType.TEXT, isNullable: true },
    { name: 'vapiContactId', label: 'VAPI Contact ID', type: FieldType.TEXT, isNullable: true },
    { name: 'ghlContactId', label: 'GHL Contact ID', type: FieldType.TEXT, isNullable: true },
  ],
});
